Iss23
NorthernWidget/Margay_Library pull request #24
Opened 2022-04-26 09:04 UTC by ericbarefoot

This change solves a problem with logging from the onboard ATC. The onboard ATC allows readings for analog voltage up to 18 bits of precision, but the typical `Margay::run()` method cannot access values from this device. 

This is because the ATC actually communicates with I2C, and so external sensors (which are typically read from I2C) might have address clashes. `Margay::run()` solves this by turning the external I2C bus on, reading data, then turning it off, but we want to also read from the internal I2C in the same breath! 

Thus, we have now added a switch to the `Margay::getVoltage()` method to test if the external I2C bus is on, and if it is, turn it off, take a reading from the ADC, then turn external I2C back on again. 

Should close #23

2022-05-02 07:40 UTC, awickert requested changes
Hey @ericbarefoot,

Thanks for all this! The `initADC()` function looks like a good addition.

Now for a few thoughts and requested changes, and I imagine that @bschulz1701 may have some as well.

1. I can see your idea behind `bool extI2COn = digitalRead(SD_CD);` being that you can first check whether internal or external I2C communcations are shunted to be open. However, the SD card communicates over SPI, and so this probably won't work.
2. Related to (1), could you add additional comments about why you're doing what you're doing in the code? This would be helpful: I think I just knew what was going on re:(1) because you told me about your idea, which in principle, is good.
3. In order to execute your idea in (1), we could establish a variable with global scope that stores this I2C internal/external state, and then switch this inside the `externalI2C()` function. (Or we could change the `externalI2C` function to a `switchI2C` function, with `EXTERNAL` or `INTERNAL` being a defined boolean set of parameters.
4. For general tidiness, I would include `return val;` outside of the `if`-statement. Indeed, I might refactor the whole thing to have `if`s wrapping the on/off toggles and the same code within, for closer readability to the true logical flow.

2022-05-03 12:55 UTC, ericbarefoot commented
ok @awickert, this should do what you mentioned, I have fixed the typo, added some comments, and established a separate function to "close the farm gate," dependent on the state at the beginning of the function. This relies on a class-wide variable that I introduced that stores the state of the I2C bus

2022-05-03 13:56 UTC, awickert requested changes
Could you check these function renames for general code readability?
* `farmGate` function will both "open" and "close" it
* `initialState` is specifically of the *external* I2C, with the internal connection being toggled opposite

2022-05-03 13:56 UTC, awickert commented on src/Margay.cpp
> +	switchExternalI2C(ON); // re-allow external I2C
Remove: No longer needed with the farmGateI2C function
```suggestion
```

2022-05-03 13:56 UTC, awickert commented on src/Margay.cpp
> +	closeFarmGateI2C(initialStateI2C);
Can open or close gate, so:
```suggestion
	farmGateI2C(initialStateExternI2C);
```

2022-05-03 13:56 UTC, awickert commented on src/Margay.cpp
> +	closeFarmGateI2C(initialStateI2C);
Can open or close gate, so:
```suggestion
	farmGateI2C(initialStateExternI2C);
```

2022-05-03 13:56 UTC, awickert commented on src/Margay.cpp
> +void Margay::closeFarmGateI2C(bool initStateI2C)
Can open or close gate, so rename:
```suggestion
void Margay::farmGateI2C(bool initStateI2C)
```

2022-05-03 13:56 UTC, awickert commented on src/Margay.cpp
> +	closeFarmGateI2C(initialStateI2C);
Can open or close gate, so rename:
```suggestion
	farmGateI2C(initialStateExternI2C);
```

2022-05-03 13:56 UTC, awickert commented on src/Margay.cpp
> +	bool initialStateI2C = digitalRead(I2C_SW);
```suggestion
	bool initialStateExternalI2C = digitalRead(I2C_SW);
```

2022-05-03 13:56 UTC, awickert commented on src/Margay.cpp
> +	// first check whether external I2C connnections are on by testing pin I2C_SW (HIGH is on)
```suggestion
	// first check whether external I2C connnections are on by testing pin I2C_SW (HIGH is on)
	// When the external I2C connection is on, the internal I2C connection is cut off.
```

2022-05-03 13:56 UTC, awickert commented on src/Margay.cpp
> +	bool initialStateI2C = digitalRead(I2C_SW);
```suggestion
	bool initialStateExternI2C = digitalRead(I2C_SW);
```

2022-05-03 13:56 UTC, awickert commented on src/Margay.cpp
> +	switchExternalI2C(OFF);
[redundant w/ farm gate]
```suggestion
```

2022-05-03 13:56 UTC, awickert commented on src/Margay.cpp
> +	bool initialStateI2C = digitalRead(I2C_SW);
```suggestion
	bool initialStateExternI2C = digitalRead(I2C_SW);
```

2022-05-03 14:14 UTC, merged